/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author tomf
 */
public class PairAppUI extends javax.swing.JFrame {

    /**
     * Creates new form PairAppUI
     */
    public PairAppUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_MainPanel = new javax.swing.JPanel();
        jPanel_Empty = new javax.swing.JPanel();
        jPanel_EntitySearch = new javax.swing.JPanel();
        jLabel_EntitySearchName = new javax.swing.JLabel();
        jLabel_EntitySearchID = new javax.swing.JLabel();
        jTextField_EntitySearchName = new javax.swing.JTextField();
        jTextField_EntitySearchID = new javax.swing.JTextField();
        jButton_EntitySearchNameOK = new javax.swing.JButton();
        jButton_EntitySearchIDOK = new javax.swing.JButton();
        jLabel_EntitySearch = new javax.swing.JLabel();
        jPanel_EntityResult = new javax.swing.JPanel();
        jLabel_EntityOccupation = new javax.swing.JLabel();
        jLabel_EntityName = new javax.swing.JLabel();
        jLabel_EntityID = new javax.swing.JLabel();
        jLabel_EntitySkill = new javax.swing.JLabel();
        jLabel_EntityPrice = new javax.swing.JLabel();
        jLabel_EntityRegion = new javax.swing.JLabel();
        jTextField_EntityName = new javax.swing.JTextField();
        jTextField_EntityID = new javax.swing.JTextField();
        jTextField_EntitySkill = new javax.swing.JTextField();
        jTextField_EntityPrice = new javax.swing.JTextField();
        jTextField_EntityRegion = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_EntityLessons = new javax.swing.JList();
        jLabel_EntityLessons = new javax.swing.JLabel();
        jButton_EntityUpdate = new javax.swing.JButton();
        jButton_EntityDelete = new javax.swing.JButton();
        jButton_EntityAddLesson = new javax.swing.JButton();
        jPanel_EntityCreate = new javax.swing.JPanel();
        jLabel_EntityCreateOccupation = new javax.swing.JLabel();
        jLabel_EntityCreateName = new javax.swing.JLabel();
        jLabel_EntityCreateSkill = new javax.swing.JLabel();
        jLabel_EntityCreatePrice = new javax.swing.JLabel();
        jLabel_EntityCreateRegion = new javax.swing.JLabel();
        jTextField_EntityCreateName = new javax.swing.JTextField();
        jTextField_EntityCreateSkill = new javax.swing.JTextField();
        jTextField_EntityCreatePrice = new javax.swing.JTextField();
        jTextField_EntityCreateRegion = new javax.swing.JTextField();
        jButton_EntityCreateOK = new javax.swing.JButton();
        jPanel_EntityUpdate = new javax.swing.JPanel();
        jLabel_EntityUpdateOccupation = new javax.swing.JLabel();
        jLabel_EntityUpdateName = new javax.swing.JLabel();
        jLabel_EntityUpdateSkill = new javax.swing.JLabel();
        jLabel_EntityUpdatePrice = new javax.swing.JLabel();
        jLabel_EntityUpdateRegion = new javax.swing.JLabel();
        jTextField_EntityUpdateName = new javax.swing.JTextField();
        jTextField_EntityUpdateSkill = new javax.swing.JTextField();
        jTextField_EntityUpdatePrice = new javax.swing.JTextField();
        jTextField_EntityUpdateRegion = new javax.swing.JTextField();
        jButton_EntityUpdateOK = new javax.swing.JButton();
        jLabel_EntityUpdateNewName = new javax.swing.JLabel();
        jTextField_EntityUpdateNewName = new javax.swing.JTextField();
        jLabel_EntityUpdateNewSkill = new javax.swing.JLabel();
        jTextField_EntityUpdateNewSkill = new javax.swing.JTextField();
        jLabel_EntityUpdateNewPrice = new javax.swing.JLabel();
        jTextField_EntityUpdateNewPrice = new javax.swing.JTextField();
        jLabel_EntityUpdateNewRegion = new javax.swing.JLabel();
        jTextField_EntityUpdateNewRegion = new javax.swing.JTextField();
        jLabel_EntityUpdateOriginalValues = new javax.swing.JLabel();
        jLabel_EntityUpdateNewValues = new javax.swing.JLabel();
        jPanel_LessonSearch = new javax.swing.JPanel();
        jLabel_LessonSearch = new javax.swing.JLabel();
        jLabel_LessonSearchID = new javax.swing.JLabel();
        jLabel_LessonSearchStudent = new javax.swing.JLabel();
        jLabel_LessonSearchTeacher = new javax.swing.JLabel();
        jLabel_LessonSearchPair = new javax.swing.JLabel();
        jTextField_LessonSearchID = new javax.swing.JTextField();
        jTextField_LessonSearchStudent = new javax.swing.JTextField();
        jTextField_LessonSearchTeacher = new javax.swing.JTextField();
        jButton_LessonSearchID = new javax.swing.JButton();
        jButton_LessonSearchStudent = new javax.swing.JButton();
        jButton_LessonSearchTeacher = new javax.swing.JButton();
        jButton_LessonSearchPair = new javax.swing.JButton();
        jPanel_LessonResult = new javax.swing.JPanel();
        jLabel_LessonResult = new javax.swing.JLabel();
        jLabel_LessonID = new javax.swing.JLabel();
        jLabel_LessonSkill = new javax.swing.JLabel();
        jLabel_LessonPrice = new javax.swing.JLabel();
        jLabel_LessonRegion = new javax.swing.JLabel();
        jTextField_LessonID = new javax.swing.JTextField();
        jTextField_LessonSkill = new javax.swing.JTextField();
        jTextField_LessonPrice = new javax.swing.JTextField();
        jTextField_LessonRegion = new javax.swing.JTextField();
        jButton_LessonLinkToStudent = new javax.swing.JButton();
        jButton_LessonLinkToTeacher = new javax.swing.JButton();
        jButton_LessonDelete = new javax.swing.JButton();
        jPanel_LessonCreate = new javax.swing.JPanel();
        jLabel_LessonCreateStudent = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_LessonCreateStudents = new javax.swing.JList();
        jButton_LessonCreateOK = new javax.swing.JButton();
        jPanel_MultipleResults = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_Results = new javax.swing.JList();
        jLabel_OccupationMultiple = new javax.swing.JLabel();
        jMenuBar_MainMenu = new javax.swing.JMenuBar();
        jMenu_Program = new javax.swing.JMenu();
        jMenuItem_Exit = new javax.swing.JMenuItem();
        jMenu_Student = new javax.swing.JMenu();
        jMenuItem_FindStudent = new javax.swing.JMenuItem();
        jMenuItem_ListAllStudents = new javax.swing.JMenuItem();
        jMenuItem_AddStudent = new javax.swing.JMenuItem();
        jMenu_Teacher = new javax.swing.JMenu();
        jMenuItem_FindTeacher = new javax.swing.JMenuItem();
        jMenuItem_ListAllTeachers = new javax.swing.JMenuItem();
        jMenuItem_AddTeacher = new javax.swing.JMenuItem();
        jMenu_Lesson = new javax.swing.JMenu();
        jMenuItem_FindLesson = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pairing application");

        jPanel_MainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel_EmptyLayout = new javax.swing.GroupLayout(jPanel_Empty);
        jPanel_Empty.setLayout(jPanel_EmptyLayout);
        jPanel_EmptyLayout.setHorizontalGroup(
            jPanel_EmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );
        jPanel_EmptyLayout.setVerticalGroup(
            jPanel_EmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );

        jPanel_MainPanel.add(jPanel_Empty, "card5");

        jLabel_EntitySearchName.setText("Search by name");

        jLabel_EntitySearchID.setText("Search by ID");

        jTextField_EntitySearchName.setText("\"name goes here\"");
        jTextField_EntitySearchName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_EntitySearchNameMouseClicked(evt);
            }
        });
        jTextField_EntitySearchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EntitySearchNameActionPerformed(evt);
            }
        });

        jTextField_EntitySearchID.setText("\"ID goes here\"");
        jTextField_EntitySearchID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_EntitySearchIDMouseClicked(evt);
            }
        });
        jTextField_EntitySearchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EntitySearchIDActionPerformed(evt);
            }
        });

        jButton_EntitySearchNameOK.setText("OK");
        jButton_EntitySearchNameOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EntitySearchNameOKActionPerformed(evt);
            }
        });

        jButton_EntitySearchIDOK.setText("OK");
        jButton_EntitySearchIDOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EntitySearchIDOKActionPerformed(evt);
            }
        });

        jLabel_EntitySearch.setText("Searching for ...");

        javax.swing.GroupLayout jPanel_EntitySearchLayout = new javax.swing.GroupLayout(jPanel_EntitySearch);
        jPanel_EntitySearch.setLayout(jPanel_EntitySearchLayout);
        jPanel_EntitySearchLayout.setHorizontalGroup(
            jPanel_EntitySearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EntitySearchLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel_EntitySearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_EntitySearchLayout.createSequentialGroup()
                        .addComponent(jLabel_EntitySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_EntitySearchLayout.createSequentialGroup()
                        .addGroup(jPanel_EntitySearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_EntitySearchName)
                            .addComponent(jLabel_EntitySearchID))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_EntitySearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_EntitySearchName, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jTextField_EntitySearchID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 403, Short.MAX_VALUE)
                        .addGroup(jPanel_EntitySearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_EntitySearchNameOK, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_EntitySearchIDOK, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel_EntitySearchLayout.setVerticalGroup(
            jPanel_EntitySearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EntitySearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_EntitySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel_EntitySearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_EntitySearchName)
                    .addComponent(jTextField_EntitySearchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_EntitySearchNameOK))
                .addGap(21, 21, 21)
                .addGroup(jPanel_EntitySearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_EntitySearchID)
                    .addComponent(jTextField_EntitySearchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_EntitySearchIDOK))
                .addContainerGap(293, Short.MAX_VALUE))
        );

        jPanel_MainPanel.add(jPanel_EntitySearch, "card2");

        jLabel_EntityOccupation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_EntityOccupation.setText("Unknown");

        jLabel_EntityName.setText("Name");

        jLabel_EntityID.setText("ID");

        jLabel_EntitySkill.setText("Skill");

        jLabel_EntityPrice.setText("Price");

        jLabel_EntityRegion.setText("Region");

        jList_EntityLessons.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList_EntityLessons);

        jLabel_EntityLessons.setText("Lessons");

        jButton_EntityUpdate.setText("Update");
        jButton_EntityUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EntityUpdateActionPerformed(evt);
            }
        });

        jButton_EntityDelete.setText("Delete");
        jButton_EntityDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EntityDeleteActionPerformed(evt);
            }
        });

        jButton_EntityAddLesson.setText("Add Lesson");
        jButton_EntityAddLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EntityAddLessonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_EntityResultLayout = new javax.swing.GroupLayout(jPanel_EntityResult);
        jPanel_EntityResult.setLayout(jPanel_EntityResultLayout);
        jPanel_EntityResultLayout.setHorizontalGroup(
            jPanel_EntityResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EntityResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_EntityResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_EntityResultLayout.createSequentialGroup()
                        .addGroup(jPanel_EntityResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_EntityName)
                            .addComponent(jLabel_EntityID)
                            .addComponent(jLabel_EntitySkill)
                            .addComponent(jLabel_EntityPrice)
                            .addComponent(jLabel_EntityRegion))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel_EntityResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_EntityName)
                            .addComponent(jTextField_EntityID)
                            .addComponent(jTextField_EntitySkill)
                            .addComponent(jTextField_EntityPrice)
                            .addComponent(jTextField_EntityRegion, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addComponent(jLabel_EntityOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_EntityUpdate)
                    .addComponent(jButton_EntityDelete)
                    .addComponent(jButton_EntityAddLesson))
                .addGap(66, 66, 66)
                .addGroup(jPanel_EntityResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_EntityLessons)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel_EntityResultLayout.setVerticalGroup(
            jPanel_EntityResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EntityResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_EntityResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_EntityOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_EntityLessons))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_EntityResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_EntityResultLayout.createSequentialGroup()
                        .addGroup(jPanel_EntityResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_EntityName)
                            .addComponent(jTextField_EntityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_EntityResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_EntityID)
                            .addComponent(jTextField_EntityID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_EntityResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_EntitySkill)
                            .addComponent(jTextField_EntitySkill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_EntityResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_EntityPrice)
                            .addComponent(jTextField_EntityPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_EntityResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_EntityRegion)
                            .addComponent(jTextField_EntityRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_EntityAddLesson)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_EntityUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_EntityDelete))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jPanel_MainPanel.add(jPanel_EntityResult, "card3");

        jLabel_EntityCreateOccupation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_EntityCreateOccupation.setText("Unknown");

        jLabel_EntityCreateName.setText("Name");

        jLabel_EntityCreateSkill.setText("Skill");

        jLabel_EntityCreatePrice.setText("Price");

        jLabel_EntityCreateRegion.setText("Region");

        jButton_EntityCreateOK.setText("Create");
        jButton_EntityCreateOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EntityCreateOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_EntityCreateLayout = new javax.swing.GroupLayout(jPanel_EntityCreate);
        jPanel_EntityCreate.setLayout(jPanel_EntityCreateLayout);
        jPanel_EntityCreateLayout.setHorizontalGroup(
            jPanel_EntityCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_EntityCreateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_EntityCreateOK, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel_EntityCreateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_EntityCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_EntityCreateOccupation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_EntityCreateLayout.createSequentialGroup()
                        .addGroup(jPanel_EntityCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_EntityCreateName)
                            .addComponent(jLabel_EntityCreateSkill)
                            .addComponent(jLabel_EntityCreatePrice)
                            .addComponent(jLabel_EntityCreateRegion))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel_EntityCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_EntityCreateName)
                            .addComponent(jTextField_EntityCreateSkill)
                            .addComponent(jTextField_EntityCreatePrice)
                            .addComponent(jTextField_EntityCreateRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(530, Short.MAX_VALUE))
        );
        jPanel_EntityCreateLayout.setVerticalGroup(
            jPanel_EntityCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EntityCreateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_EntityCreateOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_EntityCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_EntityCreateName)
                    .addComponent(jTextField_EntityCreateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_EntityCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_EntityCreateSkill)
                    .addComponent(jTextField_EntityCreateSkill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_EntityCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_EntityCreatePrice)
                    .addComponent(jTextField_EntityCreatePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_EntityCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_EntityCreateRegion)
                    .addComponent(jTextField_EntityCreateRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(jButton_EntityCreateOK, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_MainPanel.add(jPanel_EntityCreate, "card9");

        jLabel_EntityUpdateOccupation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_EntityUpdateOccupation.setText("Unknown");

        jLabel_EntityUpdateName.setText("Name");

        jLabel_EntityUpdateSkill.setText("Skill");

        jLabel_EntityUpdatePrice.setText("Price");

        jLabel_EntityUpdateRegion.setText("Region");

        jTextField_EntityUpdateName.setEditable(false);

        jTextField_EntityUpdateSkill.setEditable(false);

        jTextField_EntityUpdatePrice.setEditable(false);

        jTextField_EntityUpdateRegion.setEditable(false);

        jButton_EntityUpdateOK.setText("Update");
        jButton_EntityUpdateOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EntityUpdateOKActionPerformed(evt);
            }
        });

        jLabel_EntityUpdateNewName.setText("Name");

        jTextField_EntityUpdateNewName.setText("\"new name\"");
        jTextField_EntityUpdateNewName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_EntityUpdateNewNameMouseClicked(evt);
            }
        });

        jLabel_EntityUpdateNewSkill.setText("Skill");

        jTextField_EntityUpdateNewSkill.setText("\"new skill\"");
        jTextField_EntityUpdateNewSkill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_EntityUpdateNewSkillMouseClicked(evt);
            }
        });

        jLabel_EntityUpdateNewPrice.setText("Price");

        jTextField_EntityUpdateNewPrice.setText("\"new price\"");
        jTextField_EntityUpdateNewPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_EntityUpdateNewPriceMouseClicked(evt);
            }
        });

        jLabel_EntityUpdateNewRegion.setText("Region");

        jTextField_EntityUpdateNewRegion.setText("\"new region\"");
        jTextField_EntityUpdateNewRegion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_EntityUpdateNewRegionMouseClicked(evt);
            }
        });

        jLabel_EntityUpdateOriginalValues.setText("Original values");

        jLabel_EntityUpdateNewValues.setText("New values");

        javax.swing.GroupLayout jPanel_EntityUpdateLayout = new javax.swing.GroupLayout(jPanel_EntityUpdate);
        jPanel_EntityUpdate.setLayout(jPanel_EntityUpdateLayout);
        jPanel_EntityUpdateLayout.setHorizontalGroup(
            jPanel_EntityUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EntityUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_EntityUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_EntityUpdateLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_EntityUpdateOK, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_EntityUpdateLayout.createSequentialGroup()
                        .addGroup(jPanel_EntityUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_EntityUpdateOccupation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel_EntityUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel_EntityUpdateLayout.createSequentialGroup()
                                    .addGroup(jPanel_EntityUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_EntityUpdateName)
                                        .addComponent(jLabel_EntityUpdateSkill)
                                        .addComponent(jLabel_EntityUpdatePrice)
                                        .addComponent(jLabel_EntityUpdateRegion))
                                    .addGap(42, 42, 42)
                                    .addGroup(jPanel_EntityUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField_EntityUpdateSkill)
                                        .addComponent(jTextField_EntityUpdatePrice)
                                        .addComponent(jTextField_EntityUpdateRegion, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(jTextField_EntityUpdateName)))
                                .addComponent(jLabel_EntityUpdateOriginalValues)))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel_EntityUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_EntityUpdateNewValues)
                            .addGroup(jPanel_EntityUpdateLayout.createSequentialGroup()
                                .addGroup(jPanel_EntityUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_EntityUpdateNewName)
                                    .addComponent(jLabel_EntityUpdateNewSkill)
                                    .addComponent(jLabel_EntityUpdateNewPrice)
                                    .addComponent(jLabel_EntityUpdateNewRegion))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel_EntityUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_EntityUpdateNewName)
                                    .addComponent(jTextField_EntityUpdateNewSkill)
                                    .addComponent(jTextField_EntityUpdateNewPrice)
                                    .addComponent(jTextField_EntityUpdateNewRegion, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                        .addGap(0, 297, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_EntityUpdateLayout.setVerticalGroup(
            jPanel_EntityUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EntityUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_EntityUpdateOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_EntityUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_EntityUpdateOriginalValues)
                    .addComponent(jLabel_EntityUpdateNewValues))
                .addGap(18, 18, 18)
                .addGroup(jPanel_EntityUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_EntityUpdateName)
                    .addComponent(jTextField_EntityUpdateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_EntityUpdateNewName)
                    .addComponent(jTextField_EntityUpdateNewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_EntityUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_EntityUpdateSkill)
                    .addComponent(jTextField_EntityUpdateSkill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_EntityUpdateNewSkill)
                    .addComponent(jTextField_EntityUpdateNewSkill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_EntityUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_EntityUpdatePrice)
                    .addComponent(jTextField_EntityUpdatePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_EntityUpdateNewPrice)
                    .addComponent(jTextField_EntityUpdateNewPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_EntityUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_EntityUpdateRegion)
                    .addComponent(jTextField_EntityUpdateRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_EntityUpdateNewRegion)
                    .addComponent(jTextField_EntityUpdateNewRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(jButton_EntityUpdateOK, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_MainPanel.add(jPanel_EntityUpdate, "card9");

        jLabel_LessonSearch.setText("Searching for lesson");

        jLabel_LessonSearchID.setText("Search by ID");

        jLabel_LessonSearchStudent.setText("Search by student");

        jLabel_LessonSearchTeacher.setText("Search by teacher");

        jLabel_LessonSearchPair.setText("Search by student/teacher pair");

        jTextField_LessonSearchID.setText("\"ID goes here\"");
        jTextField_LessonSearchID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_LessonSearchIDMouseClicked(evt);
            }
        });
        jTextField_LessonSearchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LessonSearchIDActionPerformed(evt);
            }
        });

        jTextField_LessonSearchStudent.setText("\"name goes here\"");
        jTextField_LessonSearchStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_LessonSearchStudentMouseClicked(evt);
            }
        });
        jTextField_LessonSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LessonSearchStudentActionPerformed(evt);
            }
        });

        jTextField_LessonSearchTeacher.setText("\"name goes here\"");
        jTextField_LessonSearchTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_LessonSearchTeacherMouseClicked(evt);
            }
        });

        jButton_LessonSearchID.setText("OK");
        jButton_LessonSearchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LessonSearchIDActionPerformed(evt);
            }
        });

        jButton_LessonSearchStudent.setText("OK");
        jButton_LessonSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LessonSearchStudentActionPerformed(evt);
            }
        });

        jButton_LessonSearchTeacher.setText("OK");
        jButton_LessonSearchTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LessonSearchTeacherActionPerformed(evt);
            }
        });

        jButton_LessonSearchPair.setText("OK");
        jButton_LessonSearchPair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LessonSearchPairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_LessonSearchLayout = new javax.swing.GroupLayout(jPanel_LessonSearch);
        jPanel_LessonSearch.setLayout(jPanel_LessonSearchLayout);
        jPanel_LessonSearchLayout.setHorizontalGroup(
            jPanel_LessonSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LessonSearchLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel_LessonSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_LessonSearchLayout.createSequentialGroup()
                        .addGroup(jPanel_LessonSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_LessonSearchID)
                            .addComponent(jLabel_LessonSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_LessonSearchTeacher))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel_LessonSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_LessonSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField_LessonSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_LessonSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField_LessonSearchTeacher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel_LessonSearchPair)
                    .addComponent(jLabel_LessonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 374, Short.MAX_VALUE)
                .addGroup(jPanel_LessonSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_LessonSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton_LessonSearchID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_LessonSearchStudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_LessonSearchTeacher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton_LessonSearchPair))
                .addContainerGap())
        );
        jPanel_LessonSearchLayout.setVerticalGroup(
            jPanel_LessonSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LessonSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_LessonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel_LessonSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_LessonSearchID)
                    .addComponent(jTextField_LessonSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_LessonSearchID))
                .addGap(21, 21, 21)
                .addGroup(jPanel_LessonSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_LessonSearchStudent)
                    .addComponent(jTextField_LessonSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_LessonSearchStudent))
                .addGap(18, 18, 18)
                .addGroup(jPanel_LessonSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_LessonSearchTeacher)
                    .addComponent(jTextField_LessonSearchTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_LessonSearchTeacher))
                .addGap(18, 18, 18)
                .addGroup(jPanel_LessonSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_LessonSearchPair)
                    .addComponent(jButton_LessonSearchPair))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jPanel_MainPanel.add(jPanel_LessonSearch, "card7");

        jLabel_LessonResult.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_LessonResult.setText("Lesson");

        jLabel_LessonID.setText("ID");

        jLabel_LessonSkill.setText("Skill");

        jLabel_LessonPrice.setText("Price");

        jLabel_LessonRegion.setText("Region");

        jTextField_LessonRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LessonRegionActionPerformed(evt);
            }
        });

        jButton_LessonLinkToStudent.setText("Student");
        jButton_LessonLinkToStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LessonLinkToStudentActionPerformed(evt);
            }
        });

        jButton_LessonLinkToTeacher.setText("Teacher");
        jButton_LessonLinkToTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LessonLinkToTeacherActionPerformed(evt);
            }
        });

        jButton_LessonDelete.setText("Delete");
        jButton_LessonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LessonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_LessonResultLayout = new javax.swing.GroupLayout(jPanel_LessonResult);
        jPanel_LessonResult.setLayout(jPanel_LessonResultLayout);
        jPanel_LessonResultLayout.setHorizontalGroup(
            jPanel_LessonResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LessonResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_LessonResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_LessonResult)
                    .addGroup(jPanel_LessonResultLayout.createSequentialGroup()
                        .addGroup(jPanel_LessonResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_LessonRegion)
                            .addComponent(jLabel_LessonPrice)
                            .addComponent(jLabel_LessonSkill)
                            .addComponent(jLabel_LessonID))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_LessonResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_LessonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_LessonResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_LessonSkill)
                                .addComponent(jTextField_LessonRegion, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(jTextField_LessonPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(jButton_LessonLinkToStudent)
                                .addComponent(jButton_LessonLinkToTeacher)
                                .addComponent(jTextField_LessonID)))))
                .addGap(0, 554, Short.MAX_VALUE))
        );
        jPanel_LessonResultLayout.setVerticalGroup(
            jPanel_LessonResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LessonResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_LessonResult)
                .addGap(15, 15, 15)
                .addGroup(jPanel_LessonResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_LessonID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_LessonID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_LessonResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_LessonSkill)
                    .addComponent(jTextField_LessonSkill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_LessonResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_LessonPrice)
                    .addComponent(jTextField_LessonRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_LessonResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_LessonRegion)
                    .addComponent(jTextField_LessonPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_LessonLinkToStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_LessonLinkToTeacher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(jButton_LessonDelete)
                .addGap(26, 26, 26))
        );

        jPanel_MainPanel.add(jPanel_LessonResult, "card6");

        jLabel_LessonCreateStudent.setText("Select ...");

        jList_LessonCreateStudents.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList_LessonCreateStudents);

        jButton_LessonCreateOK.setText("Create lesson");
        jButton_LessonCreateOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LessonCreateOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_LessonCreateLayout = new javax.swing.GroupLayout(jPanel_LessonCreate);
        jPanel_LessonCreate.setLayout(jPanel_LessonCreateLayout);
        jPanel_LessonCreateLayout.setHorizontalGroup(
            jPanel_LessonCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LessonCreateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_LessonCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_LessonCreateStudent)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 423, Short.MAX_VALUE)
                .addComponent(jButton_LessonCreateOK, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_LessonCreateLayout.setVerticalGroup(
            jPanel_LessonCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_LessonCreateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_LessonCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_LessonCreateLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_LessonCreateOK, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_LessonCreateLayout.createSequentialGroup()
                        .addComponent(jLabel_LessonCreateStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel_MainPanel.add(jPanel_LessonCreate, "card8");

        jList_Results.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList_Results.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList_Results);

        jLabel_OccupationMultiple.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_OccupationMultiple.setText("Unknown");

        javax.swing.GroupLayout jPanel_MultipleResultsLayout = new javax.swing.GroupLayout(jPanel_MultipleResults);
        jPanel_MultipleResults.setLayout(jPanel_MultipleResultsLayout);
        jPanel_MultipleResultsLayout.setHorizontalGroup(
            jPanel_MultipleResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MultipleResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_MultipleResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_OccupationMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(471, Short.MAX_VALUE))
        );
        jPanel_MultipleResultsLayout.setVerticalGroup(
            jPanel_MultipleResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_MultipleResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_OccupationMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jPanel_MainPanel.add(jPanel_MultipleResults, "card4");

        jMenu_Program.setText("Program");

        jMenuItem_Exit.setText("Exit");
        jMenuItem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ExitActionPerformed(evt);
            }
        });
        jMenuItem_Exit.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenuItem_ExitMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenu_Program.add(jMenuItem_Exit);

        jMenuBar_MainMenu.add(jMenu_Program);

        jMenu_Student.setText("Student");

        jMenuItem_FindStudent.setText("Find student");
        jMenuItem_FindStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_FindStudentActionPerformed(evt);
            }
        });
        jMenu_Student.add(jMenuItem_FindStudent);

        jMenuItem_ListAllStudents.setText("List all students");
        jMenuItem_ListAllStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ListAllStudentsActionPerformed(evt);
            }
        });
        jMenu_Student.add(jMenuItem_ListAllStudents);

        jMenuItem_AddStudent.setText("Add student");
        jMenuItem_AddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AddStudentActionPerformed(evt);
            }
        });
        jMenu_Student.add(jMenuItem_AddStudent);

        jMenuBar_MainMenu.add(jMenu_Student);

        jMenu_Teacher.setText("Teacher");

        jMenuItem_FindTeacher.setText("Find teacher");
        jMenuItem_FindTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_FindTeacherActionPerformed(evt);
            }
        });
        jMenu_Teacher.add(jMenuItem_FindTeacher);

        jMenuItem_ListAllTeachers.setText("List all teachers");
        jMenuItem_ListAllTeachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ListAllTeachersActionPerformed(evt);
            }
        });
        jMenu_Teacher.add(jMenuItem_ListAllTeachers);

        jMenuItem_AddTeacher.setText("Add teacher");
        jMenuItem_AddTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AddTeacherActionPerformed(evt);
            }
        });
        jMenu_Teacher.add(jMenuItem_AddTeacher);

        jMenuBar_MainMenu.add(jMenu_Teacher);

        jMenu_Lesson.setText("Lesson");

        jMenuItem_FindLesson.setText("Find lesson");
        jMenuItem_FindLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_FindLessonActionPerformed(evt);
            }
        });
        jMenu_Lesson.add(jMenuItem_FindLesson);

        jMenuBar_MainMenu.add(jMenu_Lesson);

        setJMenuBar(jMenuBar_MainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );

        setBounds(0, 0, 731, 464);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_LessonCreateOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LessonCreateOKActionPerformed
        // TODO add your handling code here:
        jPanel_MainPanel.removeAll();
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();

        jPanel_MainPanel.add(jPanel_Empty);
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();
        JOptionPane.showMessageDialog(null, "Creating prolly ok.");
    }//GEN-LAST:event_jButton_LessonCreateOKActionPerformed

    private void jButton_LessonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LessonDeleteActionPerformed
        // TODO add your handling code here:
        jPanel_MainPanel.removeAll();
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();

        jPanel_MainPanel.add(jPanel_Empty);
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();
        JOptionPane.showMessageDialog(null, "Deletion prolly ok.");
    }//GEN-LAST:event_jButton_LessonDeleteActionPerformed

    private void jButton_LessonLinkToTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LessonLinkToTeacherActionPerformed
        // TODO add your handling code here:
        jPanel_MainPanel.removeAll();
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();

        jLabel_EntityOccupation.setText("Teacher");
        jPanel_MainPanel.add(jPanel_EntityResult);
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();
    }//GEN-LAST:event_jButton_LessonLinkToTeacherActionPerformed

    private void jButton_LessonLinkToStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LessonLinkToStudentActionPerformed
        // TODO add your handling code here:
        jPanel_MainPanel.removeAll();
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();

        jLabel_EntityOccupation.setText("Student");
        jPanel_MainPanel.add(jPanel_EntityResult);
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();
    }//GEN-LAST:event_jButton_LessonLinkToStudentActionPerformed

    private void jTextField_LessonRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LessonRegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LessonRegionActionPerformed

    private void jButton_LessonSearchPairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LessonSearchPairActionPerformed
        // TODO add your handling code here:
        jPanel_MainPanel.removeAll();
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();

        jPanel_MainPanel.add(jPanel_LessonResult);
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();
    }//GEN-LAST:event_jButton_LessonSearchPairActionPerformed

    private void jButton_LessonSearchTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LessonSearchTeacherActionPerformed
        // TODO add your handling code here:
        jPanel_MainPanel.removeAll();
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();

        jLabel_OccupationMultiple.setText("Teacher's lessons");
        jPanel_MainPanel.add(jPanel_MultipleResults);
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();
    }//GEN-LAST:event_jButton_LessonSearchTeacherActionPerformed

    private void jButton_LessonSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LessonSearchStudentActionPerformed
        // TODO add your handling code here:
        jPanel_MainPanel.removeAll();
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();

        jLabel_OccupationMultiple.setText("Student's lessons");
        jPanel_MainPanel.add(jPanel_MultipleResults);
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();
    }//GEN-LAST:event_jButton_LessonSearchStudentActionPerformed

    private void jButton_LessonSearchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LessonSearchIDActionPerformed
        // TODO add your handling code here:
        jPanel_MainPanel.removeAll();
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();

        jPanel_MainPanel.add(jPanel_LessonResult);
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();
    }//GEN-LAST:event_jButton_LessonSearchIDActionPerformed

    private void jTextField_LessonSearchTeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_LessonSearchTeacherMouseClicked
        // TODO add your handling code here:
        jTextField_LessonSearchTeacher.setText("");
    }//GEN-LAST:event_jTextField_LessonSearchTeacherMouseClicked

    private void jTextField_LessonSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LessonSearchStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LessonSearchStudentActionPerformed

    private void jTextField_LessonSearchStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_LessonSearchStudentMouseClicked
        // TODO add your handling code here:
        jTextField_LessonSearchStudent.setText("");
    }//GEN-LAST:event_jTextField_LessonSearchStudentMouseClicked

    private void jTextField_LessonSearchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LessonSearchIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LessonSearchIDActionPerformed

    private void jTextField_LessonSearchIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_LessonSearchIDMouseClicked
        // TODO add your handling code here:
        jTextField_LessonSearchID.setText("");
    }//GEN-LAST:event_jTextField_LessonSearchIDMouseClicked

    private void jTextField_EntityUpdateNewRegionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_EntityUpdateNewRegionMouseClicked
        // TODO add your handling code here:
        jTextField_EntityUpdateNewRegion.setText("");
    }//GEN-LAST:event_jTextField_EntityUpdateNewRegionMouseClicked

    private void jTextField_EntityUpdateNewPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_EntityUpdateNewPriceMouseClicked
        // TODO add your handling code here:
        jTextField_EntityUpdateNewPrice.setText("");
    }//GEN-LAST:event_jTextField_EntityUpdateNewPriceMouseClicked

    private void jTextField_EntityUpdateNewSkillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_EntityUpdateNewSkillMouseClicked
        // TODO add your handling code here:
        jTextField_EntityUpdateNewSkill.setText("");
    }//GEN-LAST:event_jTextField_EntityUpdateNewSkillMouseClicked

    private void jTextField_EntityUpdateNewNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_EntityUpdateNewNameMouseClicked
        // TODO add your handling code here:
        jTextField_EntityUpdateNewName.setText("");
    }//GEN-LAST:event_jTextField_EntityUpdateNewNameMouseClicked

    private void jButton_EntityUpdateOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EntityUpdateOKActionPerformed
        // TODO add your handling code here:
        jPanel_MainPanel.removeAll();
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();

        jPanel_MainPanel.add(jPanel_Empty);
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();
        JOptionPane.showMessageDialog(null, "Updating prolly ok.");
    }//GEN-LAST:event_jButton_EntityUpdateOKActionPerformed

    private void jButton_EntityCreateOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EntityCreateOKActionPerformed
        // TODO add your handling code here:
        jPanel_MainPanel.removeAll();
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();

        jPanel_MainPanel.add(jPanel_Empty);
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();
        JOptionPane.showMessageDialog(null, "Creation prolly ok.");
    }//GEN-LAST:event_jButton_EntityCreateOKActionPerformed

    private void jButton_EntityAddLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EntityAddLessonActionPerformed
        // TODO add your handling code here:
        jPanel_MainPanel.removeAll();
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();

        if (jLabel_EntityOccupation.getText().toLowerCase().equals("teacher")){
            jLabel_LessonCreateStudent.setText("Select student");
        }
        else {
            jLabel_LessonCreateStudent.setText("Select teacher");
        }

        jPanel_MainPanel.add(jPanel_LessonCreate);
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();
    }//GEN-LAST:event_jButton_EntityAddLessonActionPerformed

    private void jButton_EntityDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EntityDeleteActionPerformed
        // TODO add your handling code here:
        jPanel_MainPanel.removeAll();
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();

        jPanel_MainPanel.add(jPanel_Empty);
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();
        JOptionPane.showMessageDialog(null, "Deletion prolly ok.");
    }//GEN-LAST:event_jButton_EntityDeleteActionPerformed

    private void jButton_EntityUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EntityUpdateActionPerformed
        // TODO add your handling code here:
        jPanel_MainPanel.removeAll();
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();

        jLabel_EntityUpdateOccupation.setText("Update " + jLabel_EntityOccupation.getText().toLowerCase() );
        jPanel_MainPanel.add(jPanel_EntityUpdate);
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();
    }//GEN-LAST:event_jButton_EntityUpdateActionPerformed

    private void jButton_EntitySearchIDOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EntitySearchIDOKActionPerformed
        // TODO add your handling code here:
        jPanel_MainPanel.removeAll();
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();

        jPanel_MainPanel.add(jPanel_EntityResult);
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();
    }//GEN-LAST:event_jButton_EntitySearchIDOKActionPerformed

    private void jButton_EntitySearchNameOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EntitySearchNameOKActionPerformed
        // TODO add your handling code here:
        jPanel_MainPanel.removeAll();
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();

        jPanel_MainPanel.add(jPanel_EntityResult);
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();
    }//GEN-LAST:event_jButton_EntitySearchNameOKActionPerformed

    private void jTextField_EntitySearchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EntitySearchIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EntitySearchIDActionPerformed

    private void jTextField_EntitySearchIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_EntitySearchIDMouseClicked
        // TODO add your handling code here:
        jTextField_EntitySearchID.setText("");
    }//GEN-LAST:event_jTextField_EntitySearchIDMouseClicked

    private void jTextField_EntitySearchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EntitySearchNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EntitySearchNameActionPerformed

    private void jTextField_EntitySearchNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_EntitySearchNameMouseClicked
        // TODO add your handling code here:
        jTextField_EntitySearchName.setText("");
    }//GEN-LAST:event_jTextField_EntitySearchNameMouseClicked

    private void jMenuItem_FindLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_FindLessonActionPerformed
        // TODO add your handling code here:
        jPanel_MainPanel.removeAll();
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();

        jPanel_MainPanel.add(jPanel_LessonSearch);
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();
    }//GEN-LAST:event_jMenuItem_FindLessonActionPerformed

    private void jMenuItem_AddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AddTeacherActionPerformed
        // TODO add your handling code here:
        jPanel_MainPanel.removeAll();
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();

        jLabel_EntityCreateOccupation.setText("Create new teacher");
        jPanel_MainPanel.add(jPanel_EntityCreate);
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();
    }//GEN-LAST:event_jMenuItem_AddTeacherActionPerformed

    private void jMenuItem_ListAllTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ListAllTeachersActionPerformed
        // TODO add your handling code here:
        jPanel_MainPanel.removeAll();
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();

        jLabel_OccupationMultiple.setText("Teachers");
        jPanel_MainPanel.add(jPanel_MultipleResults);
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();
    }//GEN-LAST:event_jMenuItem_ListAllTeachersActionPerformed

    private void jMenuItem_FindTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_FindTeacherActionPerformed
        // TODO add your handling code here:
        jPanel_MainPanel.removeAll();
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();

        jLabel_EntitySearch.setText("Searching for teacher");
        jLabel_EntityOccupation.setText("Teacher");
        jPanel_MainPanel.add(jPanel_EntitySearch);
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();
    }//GEN-LAST:event_jMenuItem_FindTeacherActionPerformed

    private void jMenuItem_AddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AddStudentActionPerformed
        // TODO add your handling code here:
        jPanel_MainPanel.removeAll();
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();

        jLabel_EntityCreateOccupation.setText("Create new student");
        jPanel_MainPanel.add(jPanel_EntityCreate);
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();
    }//GEN-LAST:event_jMenuItem_AddStudentActionPerformed

    private void jMenuItem_ListAllStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ListAllStudentsActionPerformed
        // TODO add your handling code here:
        jPanel_MainPanel.removeAll();
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();

        jLabel_OccupationMultiple.setText("Students");
        jPanel_MainPanel.add(jPanel_MultipleResults);
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();
    }//GEN-LAST:event_jMenuItem_ListAllStudentsActionPerformed

    private void jMenuItem_FindStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_FindStudentActionPerformed
        // TODO add your handling code here:
        jPanel_MainPanel.removeAll();
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();

        jLabel_EntitySearch.setText("Searching for student");
        jLabel_EntityOccupation.setText("Student");
        jPanel_MainPanel.add(jPanel_EntitySearch);
        jPanel_MainPanel.repaint();
        jPanel_MainPanel.revalidate();
    }//GEN-LAST:event_jMenuItem_FindStudentActionPerformed

    private void jMenuItem_ExitMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenuItem_ExitMenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_ExitMenuKeyPressed

    private void jMenuItem_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PairAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PairAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PairAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PairAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PairAppUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_EntityAddLesson;
    private javax.swing.JButton jButton_EntityCreateOK;
    private javax.swing.JButton jButton_EntityDelete;
    private javax.swing.JButton jButton_EntitySearchIDOK;
    private javax.swing.JButton jButton_EntitySearchNameOK;
    private javax.swing.JButton jButton_EntityUpdate;
    private javax.swing.JButton jButton_EntityUpdateOK;
    private javax.swing.JButton jButton_LessonCreateOK;
    private javax.swing.JButton jButton_LessonDelete;
    private javax.swing.JButton jButton_LessonLinkToStudent;
    private javax.swing.JButton jButton_LessonLinkToTeacher;
    private javax.swing.JButton jButton_LessonSearchID;
    private javax.swing.JButton jButton_LessonSearchPair;
    private javax.swing.JButton jButton_LessonSearchStudent;
    private javax.swing.JButton jButton_LessonSearchTeacher;
    private javax.swing.JLabel jLabel_EntityCreateName;
    private javax.swing.JLabel jLabel_EntityCreateOccupation;
    private javax.swing.JLabel jLabel_EntityCreatePrice;
    private javax.swing.JLabel jLabel_EntityCreateRegion;
    private javax.swing.JLabel jLabel_EntityCreateSkill;
    private javax.swing.JLabel jLabel_EntityID;
    private javax.swing.JLabel jLabel_EntityLessons;
    private javax.swing.JLabel jLabel_EntityName;
    private javax.swing.JLabel jLabel_EntityOccupation;
    private javax.swing.JLabel jLabel_EntityPrice;
    private javax.swing.JLabel jLabel_EntityRegion;
    private javax.swing.JLabel jLabel_EntitySearch;
    private javax.swing.JLabel jLabel_EntitySearchID;
    private javax.swing.JLabel jLabel_EntitySearchName;
    private javax.swing.JLabel jLabel_EntitySkill;
    private javax.swing.JLabel jLabel_EntityUpdateName;
    private javax.swing.JLabel jLabel_EntityUpdateNewName;
    private javax.swing.JLabel jLabel_EntityUpdateNewPrice;
    private javax.swing.JLabel jLabel_EntityUpdateNewRegion;
    private javax.swing.JLabel jLabel_EntityUpdateNewSkill;
    private javax.swing.JLabel jLabel_EntityUpdateNewValues;
    private javax.swing.JLabel jLabel_EntityUpdateOccupation;
    private javax.swing.JLabel jLabel_EntityUpdateOriginalValues;
    private javax.swing.JLabel jLabel_EntityUpdatePrice;
    private javax.swing.JLabel jLabel_EntityUpdateRegion;
    private javax.swing.JLabel jLabel_EntityUpdateSkill;
    private javax.swing.JLabel jLabel_LessonCreateStudent;
    private javax.swing.JLabel jLabel_LessonID;
    private javax.swing.JLabel jLabel_LessonPrice;
    private javax.swing.JLabel jLabel_LessonRegion;
    private javax.swing.JLabel jLabel_LessonResult;
    private javax.swing.JLabel jLabel_LessonSearch;
    private javax.swing.JLabel jLabel_LessonSearchID;
    private javax.swing.JLabel jLabel_LessonSearchPair;
    private javax.swing.JLabel jLabel_LessonSearchStudent;
    private javax.swing.JLabel jLabel_LessonSearchTeacher;
    private javax.swing.JLabel jLabel_LessonSkill;
    private javax.swing.JLabel jLabel_OccupationMultiple;
    private javax.swing.JList jList_EntityLessons;
    private javax.swing.JList jList_LessonCreateStudents;
    private javax.swing.JList jList_Results;
    private javax.swing.JMenuBar jMenuBar_MainMenu;
    private javax.swing.JMenuItem jMenuItem_AddStudent;
    private javax.swing.JMenuItem jMenuItem_AddTeacher;
    private javax.swing.JMenuItem jMenuItem_Exit;
    private javax.swing.JMenuItem jMenuItem_FindLesson;
    private javax.swing.JMenuItem jMenuItem_FindStudent;
    private javax.swing.JMenuItem jMenuItem_FindTeacher;
    private javax.swing.JMenuItem jMenuItem_ListAllStudents;
    private javax.swing.JMenuItem jMenuItem_ListAllTeachers;
    private javax.swing.JMenu jMenu_Lesson;
    private javax.swing.JMenu jMenu_Program;
    private javax.swing.JMenu jMenu_Student;
    private javax.swing.JMenu jMenu_Teacher;
    private javax.swing.JPanel jPanel_Empty;
    private javax.swing.JPanel jPanel_EntityCreate;
    private javax.swing.JPanel jPanel_EntityResult;
    private javax.swing.JPanel jPanel_EntitySearch;
    private javax.swing.JPanel jPanel_EntityUpdate;
    private javax.swing.JPanel jPanel_LessonCreate;
    private javax.swing.JPanel jPanel_LessonResult;
    private javax.swing.JPanel jPanel_LessonSearch;
    private javax.swing.JPanel jPanel_MainPanel;
    private javax.swing.JPanel jPanel_MultipleResults;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField_EntityCreateName;
    private javax.swing.JTextField jTextField_EntityCreatePrice;
    private javax.swing.JTextField jTextField_EntityCreateRegion;
    private javax.swing.JTextField jTextField_EntityCreateSkill;
    private javax.swing.JTextField jTextField_EntityID;
    private javax.swing.JTextField jTextField_EntityName;
    private javax.swing.JTextField jTextField_EntityPrice;
    private javax.swing.JTextField jTextField_EntityRegion;
    private javax.swing.JTextField jTextField_EntitySearchID;
    private javax.swing.JTextField jTextField_EntitySearchName;
    private javax.swing.JTextField jTextField_EntitySkill;
    private javax.swing.JTextField jTextField_EntityUpdateName;
    private javax.swing.JTextField jTextField_EntityUpdateNewName;
    private javax.swing.JTextField jTextField_EntityUpdateNewPrice;
    private javax.swing.JTextField jTextField_EntityUpdateNewRegion;
    private javax.swing.JTextField jTextField_EntityUpdateNewSkill;
    private javax.swing.JTextField jTextField_EntityUpdatePrice;
    private javax.swing.JTextField jTextField_EntityUpdateRegion;
    private javax.swing.JTextField jTextField_EntityUpdateSkill;
    private javax.swing.JTextField jTextField_LessonID;
    private javax.swing.JTextField jTextField_LessonPrice;
    private javax.swing.JTextField jTextField_LessonRegion;
    private javax.swing.JTextField jTextField_LessonSearchID;
    private javax.swing.JTextField jTextField_LessonSearchStudent;
    private javax.swing.JTextField jTextField_LessonSearchTeacher;
    private javax.swing.JTextField jTextField_LessonSkill;
    // End of variables declaration//GEN-END:variables
}
