CREATE TABLE STUDENT (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "FULLNAME" VARCHAR(50),
    "LEVEL" INTEGER NOT NULL,
    "DETAILS" VARCHAR(50)
 );
CREATE TABLE TEACHER (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "FULLNAME" VARCHAR(50),
    "LEVEL" INTEGER NOT NULL,
    "DETAILS" VARCHAR(50)
 );
CREATE TABLE LESSON (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "START" DATE,
    "DURATION" INTEGER,
    "PRICE" BIGINT,
    "NOTES" VARCHAR(255),
    "STUDENTID" BIGINT REFERENCES STUDENT (ID),
    "TEACHERID" BIGINT REFERENCES TEACHER (ID),
 );