-- my-test-data.sql

-- students

INSERT INTO STUDENT (FULLNAME, SKILL, PRICE, REGION) VALUES ('Jozko "low-skill" Mrkvicka', 1, 500.00, 'ENGLAND');

INSERT INTO STUDENT (FULLNAME, SKILL, PRICE, REGION) VALUES ('Bo "low-price" Borovsky', 5, 100.00, 'ENGLAND');

INSERT INTO STUDENT (FULLNAME, SKILL, PRICE, REGION) VALUES ('Janka "low-both" Hraskova', 1, 100.00, 'ENGLAND');

INSERT INTO STUDENT (FULLNAME, SKILL, PRICE, REGION) VALUES ('Pu "high-skill" Papi', 10, 500.00, 'ENGLAND');

INSERT INTO STUDENT (FULLNAME, SKILL, PRICE, REGION) VALUES ('Igi "high-price" Ga', 5, 1000.00, 'ENGLAND');

INSERT INTO STUDENT (FULLNAME, SKILL, PRICE, REGION) VALUES ('Petka "high-both" Plastova', 10, 1000.00, 'ENGLAND');

INSERT INTO STUDENT (FULLNAME, SKILL, PRICE, REGION) VALUES ('Zlatan "medium" Jasnysved', 5, 500.00, 'RUSSIA');

-- teachers

INSERT INTO TEACHER (FULLNAME, SKILL, PRICE, REGION) VALUES ('Igor "low-skill" Amundsen', 1, 500.00, 'ENGLAND');

INSERT INTO TEACHER (FULLNAME, SKILL, PRICE, REGION) VALUES ('Peter "low-price" Pan', 5, 100.00, 'ENGLAND');

INSERT INTO TEACHER (FULLNAME, SKILL, PRICE, REGION) VALUES ('Enriko "low-both" Ponozka', 1, 100.00, 'ENGLAND');

INSERT INTO TEACHER (FULLNAME, SKILL, PRICE, REGION) VALUES ('Stefanka "high-skill" Wonderova', 10, 500.00, 'ENGLAND');

INSERT INTO TEACHER (FULLNAME, SKILL, PRICE, REGION) VALUES ('Lujza "high-price" Silnoruka', 5, 1000.00, 'ENGLAND');

INSERT INTO TEACHER (FULLNAME, SKILL, PRICE, REGION) VALUES ('Jameson "high-both" Bond', 10, 1000.00, 'ENGLAND');

INSERT INTO TEACHER (FULLNAME, SKILL, PRICE, REGION) VALUES ('Matus "medium" Stejk', 5, 500.00, 'RUSSIA');